title: /var/log
baseurl: ""
url: "https://danilkuznetsov.github.io"
twitter_username: danny0x1
github_username:  danilkuznetsov

google_analytics:  UA-63832974-2

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
 - tips/tips.md
 - links.md
 - about.md