title: /var/log
baseurl: ""
url: "https://danilkuznetsov.github.io"
twitter_username: danny0x1
github_username:  danilkuznetsov

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed